targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "web/*.dart"
        release_options:
          dart2js_args:
            - --csp
            - --no-minify