name: imask
version: 1.0.0
description: 'dart bindings for imaskjs'

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  http: ^0.12.2
  js: ">=0.6.0 <0.7.0"

dev_dependencies:
  build_runner: ^1.7.1
  build_web_compilers: ^2.7.1